config/routes.rb
Rails.application.routes.draw do
  resources :playlists_songs

  resources :songs

  resources :playlists

  root 'static_pages#home'

  get 'static_pages/fsom'

  devise_for :users
  resources :users

end

app/models/playlists_song.rb
class PlaylistsSong < ActiveRecord::Base
  belongs_to :playlist
  belongs_to :song
end

app/controllers/playlists_songs_controller.rb
class PlaylistsSongsController < ApplicationController
  before_action :set_playlists_song, only: [:show, :edit, :update, :destroy]

  # GET /playlists_songs
  # GET /playlists_songs.json
  def index
    @playlists_songs = PlaylistsSong.all
  end

  # GET /playlists_songs/1
  # GET /playlists_songs/1.json
  def show
  end

  # GET /playlists_songs/new
  def new
    @playlists_song = PlaylistsSong.new
  end

  # GET /playlists_songs/1/edit
  def edit
  end

  # POST /playlists_songs
  # POST /playlists_songs.json
  def create
    @playlists_song = PlaylistsSong.new(playlists_song_params)

    respond_to do |format|
      if @playlists_song.save
        format.html { redirect_to @playlists_song, notice: 'Playlists song was successfully created.' }
        format.json { render :show, status: :created, location: @playlists_song }
      else
        format.html { render :new }
        format.json { render json: @playlists_song.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /playlists_songs/1
  # PATCH/PUT /playlists_songs/1.json
  def update
    respond_to do |format|
      if @playlists_song.update(playlists_song_params)
        format.html { redirect_to @playlists_song, notice: 'Playlists song was successfully updated.' }
        format.json { render :show, status: :ok, location: @playlists_song }
      else
        format.html { render :edit }
        format.json { render json: @playlists_song.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /playlists_songs/1
  # DELETE /playlists_songs/1.json
  def destroy
    @playlists_song.destroy
    respond_to do |format|
      format.html { redirect_to playlists_songs_url, notice: 'Playlists song was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_playlists_song
      @playlists_song = PlaylistsSong.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def playlists_song_params
      params.require(:playlists_song).permit(:playlist_id, :song_id)
    end
end

app/helpers/playlists_songs_helper.rb
module PlaylistsSongsHelper
end

app/views/playlists_songs/_form.html.erb
<%= form_for(@playlists_song) do |f| %>
  <% if @playlists_song.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@playlists_song.errors.count, "error") %> prohibited this playlists_song from being saved:</h2>

      <ul>
      <% @playlists_song.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :playlist_id %><br>
    <%= f.text_field :playlist_id %>
  </div>
  <div class="field">
    <%= f.label :song_id %><br>
    <%= f.text_field :song_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/playlists_songs/edit.html.erb
<h1>Editing Playlists Song</h1>

<%= render 'form' %>

<%= link_to 'Show', @playlists_song %> |
<%= link_to 'Back', playlists_songs_path %>

app/views/playlists_songs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Playlists Songs</h1>

<table>
  <thead>
    <tr>
      <th>Playlist</th>
      <th>Song</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @playlists_songs.each do |playlists_song| %>
      <tr>
        <td><%= playlists_song.playlist %></td>
        <td><%= playlists_song.song %></td>
        <td><%= link_to 'Show', playlists_song %></td>
        <td><%= link_to 'Edit', edit_playlists_song_path(playlists_song) %></td>
        <td><%= link_to 'Destroy', playlists_song, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Playlists song', new_playlists_song_path %>

app/views/playlists_songs/new.html.erb
<h1>New Playlists Song</h1>

<%= render 'form' %>

<%= link_to 'Back', playlists_songs_path %>

app/views/playlists_songs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Playlist:</strong>
  <%= @playlists_song.playlist %>
</p>

<p>
  <strong>Song:</strong>
  <%= @playlists_song.song %>
</p>

<%= link_to 'Edit', edit_playlists_song_path(@playlists_song) %> |
<%= link_to 'Back', playlists_songs_path %>