config/routes.rb
Rails.application.routes.draw do
  resources :playlists_songs

  resources :songs

  resources :playlists

  root 'static_pages#home'

  get 'static_pages/fsom'

  devise_for :users
  resources :users

end

app/models/song.rb
class Song < ActiveRecord::Base
	belongs_to :playlist
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_song, only: [:show, :edit, :update, :destroy]

  # GET /songs
  # GET /songs.json
  def index
    @songs = Song.all
  end

  # GET /songs/1
  # GET /songs/1.json
  def show
  end

  # GET /songs/new
  def new
    @song = Song.new
  end

  # GET /songs/1/edit
  def edit
  end

  # POST /songs
  # POST /songs.json
  def create
    @song = Song.new(song_params)

    respond_to do |format|
      if @song.save
        format.html { redirect_to '#', notice: 'Song was successfully created.' }
        format.json { render :show, status: :created, location: @song }
      else
        format.html { render :new }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /songs/1
  # PATCH/PUT /songs/1.json
  def update
    respond_to do |format|
      if @song.update(song_params)
        format.html { redirect_to @song, notice: 'Song was successfully updated.' }
        format.json { render :show, status: :ok, location: @song }
      else
        format.html { render :edit }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /songs/1
  # DELETE /songs/1.json
  def destroy
    @song.destroy
    respond_to do |format|
      format.html { redirect_to songs_url, notice: 'Song was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_song
      @song = Song.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def song_params
      params.require(:song).permit(:songid)
    end
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/songs/_form.html.erb
<%= form_for(@song) do |f| %>
  <% if @song.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@song.errors.count, "error") %> prohibited this song from being saved:</h2>

      <ul>
      <% @song.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :songid %><br>
    <%= f.text_field :songid %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/songs/edit.html.erb
<h1>Editing Song</h1>

<%= render 'form' %>

<%= link_to 'Show', @song %> |
<%= link_to 'Back', songs_path %>

app/views/songs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Songs</h1>

<table>
  <thead>
    <tr>
      <th>Songid</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @songs.each do |song| %>
      <tr>
        <td><%= song.songid %></td>
        <td><%= link_to 'Show', song %></td>
        <td><%= link_to 'Edit', edit_song_path(song) %></td>
        <td><%= link_to 'Destroy', song, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Song', new_song_path %>

app/views/songs/new.html.erb
<h1>New Song</h1>

<%= render 'form' %>

<%= link_to 'Back', songs_path %>

app/views/songs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Songid:</strong>
  <%= @song.songid %>
</p>

<%= link_to 'Edit', edit_song_path(@song) %> |
<%= link_to 'Back', songs_path %>