config/routes.rb
Rails.application.routes.draw do
  resources :playlists_songs

  resources :songs

  resources :playlists

  root 'static_pages#home'

  get 'static_pages/fsom'

  devise_for :users
  resources :users

end

app/models/playlist.rb
class Playlist < ActiveRecord::Base
	belongs_to :user
	validates :user_id, presence: true
	has_many :playlists_song
	has_many :songs, through: :playlists_song
end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController
  before_action :set_playlist, only: [:show, :edit, :update, :destroy]

  # GET /playlists
  # GET /playlists.json
  def index
    @playlists = Playlist.where(:user_id => current_user.id)
  end

  # GET /playlists/1
  # GET /playlists/1.json
  def show
  end

  # GET /playlists/new
  def new
    @playlist = Playlist.new
  end

  # GET /playlists/1/edit
  def edit
  end

  # POST /playlists
  # POST /playlists.json
  def create
    @playlist = Playlist.new(playlist_params)
    if user_signed_in?
      @playlist.user_id = current_user.id
    else
      raise "FUCK OFF, NOT SIGNED"
    end
    respond_to do |format|
      if @playlist.save
        format.html { redirect_to "#", notice: 'Playlist was successfully created.' }
        format.json { render :show, status: :created, location: @playlist }
      else
        format.html { render :new }
        format.json { render json: @playlist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /playlists/1
  # PATCH/PUT /playlists/1.json
  def update
    respond_to do |format|
      if @playlist.update(playlist_params)
        format.html { redirect_to @playlist, notice: 'Playlist was successfully updated.' }
        format.json { render :show, status: :ok, location: @playlist }
      else
        format.html { render :edit }
        format.json { render json: @playlist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /playlists/1
  # DELETE /playlists/1.json
  def destroy
    @playlist.destroy
    respond_to do |format|
      format.html { redirect_to playlists_url, notice: 'Playlist was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_playlist
      @playlist = Playlist.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def playlist_params
      params.require(:playlist).permit(:name)
    end
end

app/helpers/playlists_helper.rb
module PlaylistsHelper
end

app/views/playlists/_form.html.erb
<%= form_for(@playlist) do |f| %>
  <% if @playlist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@playlist.errors.count, "error") %> prohibited this playlist from being saved:</h2>

      <ul>
      <% @playlist.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/playlists/edit.html.erb
<h1>Editing Playlist</h1>

<%= render 'form' %>

<%= link_to 'Show', @playlist %> |
<%= link_to 'Back', playlists_path %>

app/views/playlists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Playlists</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @playlists.each do |playlist| %>
      <tr>
        <td><%= playlist.name %></td>
        <td><%= link_to 'Show', playlist %></td>
        <td><%= link_to 'Edit', edit_playlist_path(playlist) %></td>
        <td><%= link_to 'Destroy', playlist, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Playlist', new_playlist_path %>

app/views/playlists/new.html.erb
<h1>New Playlist</h1>

<%= render 'form' %>

<%= link_to 'Back', playlists_path %>

app/views/playlists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @playlist.name %>
</p>

<%= link_to 'Edit', edit_playlist_path(@playlist) %> |
<%= link_to 'Back', playlists_path %>